### ISSUE TITLE
Bug fixes, code refactoring and Backup Copy job support

### ISSUE THREAD

**Issue by aholiveira** [romainsi/zabbix-VB-R-SQL#10]
Hello,
First of all thank you for your work on this. It helped me get all the data from Veeam that I was looking for.

However, I took the liberty to make some changes and improvements on this, which I think you can incorporate into your code.

Attached are the following files:
- zabbix_vbr_job.ps1
- EN-Template Veeam Backup And Replication.yaml
- veeam.conf

zabbix_vbr_job.ps1 - The script was heavily refactored, some bugs fixed, date handling improved (it now handles different timezones correctly), international character handling fixed, variables moved to the top of the script, SQL connection string is now generated using the builder class and changes to reflect the template modifications. Backup copy jobs are also now supported. Adding support for other jobs types is now also easier.

EN-Template Veeam Backup And Replication.yaml - The template was also heavily modified, with key names being normalized and prefixed with "veeam" to avoid collisions, and restructured to accommodate the changes done in the data reading script. system.run was also removed and replaced by UserParameters (this removes the logging of user commands in zabbix agent log)

veeam.conf - This file should be placed under C:\Program Files\Zabbix Agent\zabbix_agentd.d
It allows the powershell script to be called via "veeam.info" UserParameter instead of system.run, which allows for less "noise" in the log and better extensibility in the future. Zabbix agent service has to be restarted after placing this file on the folder.

I have not exported the template to XML format and have not done the changes on the FR version.
Feel free to contact me if you have any question regarding the changes done.

Note: This was tested and run on a Zabbix 6.0 installation.

[zabbix-VB-R-SQL.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8665386/zabbix-VB-R-SQL.zip)

**Comment by xXxLeVIaFaNxXx** [comment]
Hi! Problem TotalJobs with argument $jobTypes = "(0, 28, 51, 63)". My Veeam B&R result query contains types 12000, 12003 etc. Where can I see which task type codes exist and what do they mean?

**Comment by aholiveira-kd** [comment]
Hello.
Those types are the ones supported by the template (Backup jobs, Backup copy, Backup Sync and Backup Tape).
If you are getting other types then you are using other jobs types than the ones supported by this template. You can probably figure this out looking doing a query "SELECT * FROM [VeeamBackup].[dbo].[Backups.View]" on the Veeam database.
Then, look into the job_name and job_target_type columns from this and correlating to what you have on Veeam.
You can then expand the script and template to support those additional types
Also note that I did this using Veeam Backup and Recovery v11 (probably v10 has the same job type codes, since [romainsi](https://github.com/romainsi) also had the same codes in his original script (I just refactored the code and added support for type 63 - Backup copy).
Hope this helps.

**Comment by aholiveira** [comment]
Hello.
Those types are the ones supported by the template (Backup jobs, Backup copy, Backup Sync and Backup Tape).
If you are getting other types then you are using other jobs types than the ones supported by this template. You can probably figure this out looking doing a query "SELECT * FROM [VeeamBackup].[dbo].[Backups.View]" on the Veeam database.
Then, look into the job_name and job_target_type columns from this and correlating to what you have on Veeam.
You can then expand the script and template to support those additional types
Also note that I did this using Veeam Backup and Recovery v11 (probably v10 has the same job type codes, since [romainsi](https://github.com/romainsi) also had the same codes in his original script (I just refactored the code and added support for type 63 - Backup copy).
Also, veeam might have this documented somewhere. I really haven't looked for it.
Hope this helps.

**Comment by aholiveira** [comment]
Those look like Agent jobs, not Backup jobs. Agent jobs are scheduled using Veeam agent, directly on the source machine. Backup jobs are scheduled on Veeam server, so they're different kinds.
Not sure of the exact difference between codes 12000 and 12003.
Adding support for those job types is possible:
- Add the corresponding codes to the $jobTypes variable (line 42) of the powershell script
- Add new keys for each job type on $typeKeys enumeration (line 182) on the powershell script (something like adding 12003="veeam.Results.AgentBackup"; )
- On Zabbix template add new discovery item, and the corresponding item and trigger prototypes. Discovery item key must match the key added on the previous step (veeam.Results.AgentBackup in the example)

I might look into this in the future but I can't promise that, so don't count on it.
I'm currently not using any of these job types on the environments I'm managing.

Hope this helps.

**Comment by romainsi** [comment]
> Hello, First of all thank you for your work on this. It helped me get all the data from Veeam that I was looking for.
> 
> However, I took the liberty to make some changes and improvements on this, which I think you can incorporate into your code.
> 
> Attached are the following files:
> 
> * zabbix_vbr_job.ps1
> * EN-Template Veeam Backup And Replication.yaml
> * veeam.conf
> 
> zabbix_vbr_job.ps1 - The script was heavily refactored, some bugs fixed, date handling improved (it now handles different timezones correctly), international character handling fixed, variables moved to the top of the script, SQL connection string is now generated using the builder class and changes to reflect the template modifications. Backup copy jobs are also now supported. Adding support for other jobs types is now also easier.
> 
> EN-Template Veeam Backup And Replication.yaml - The template was also heavily modified, with key names being normalized and prefixed with "veeam" to avoid collisions, and restructured to accommodate the changes done in the data reading script. system.run was also removed and replaced by UserParameters (this removes the logging of user commands in zabbix agent log)
> 
> veeam.conf - This file should be placed under C:\Program Files\Zabbix Agent\zabbix_agentd.d It allows the powershell script to be called via "veeam.info" UserParameter instead of system.run, which allows for less "noise" in the log and better extensibility in the future. Zabbix agent service has to be restarted after placing this file on the folder.
> 
> I have not exported the template to XML format and have not done the changes on the FR version. Feel free to contact me if you have any question regarding the changes done.
> 
> Note: This was tested and run on a Zabbix 6.0 installation.
> 
> [zabbix-VB-R-SQL.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8665386/zabbix-VB-R-SQL.zip)

Hi,

Thank you for you job ! 
I had errors on all triggers who contain 'JobReason Item' with your template :
![veeamzabbix](https://user-images.githubusercontent.com/30522413/172622255-fc8d79a0-cce2-4782-9934-b8e9969e4bea.png)

`Cannot evaluate expression: right operand """" is not a numeric value for operator at "and {2048164}"`

The problem seemed to come from the Operational data so I remove JobReason Item from trigger expression and Operational data is now {#JOBREASON} in the template.
After modification everything works fine, so I published it.

Romain.

**Comment by aholiveira** [comment]
Hello,
Thank you for merging my changes to master.
I've changed the template to fix that error. I had also noticed it but only after sending the files to you.
Attached is the fixed template (only EN version), which also has some other minor modifications.
Using {#JOBREASON} in Operational data will not give the reason on the main dashboard (you have to use {ITEM.LASTVALUEx} macro)
The only issue with the current version of the template that I have not been able to fix is that "Backup running for more than X hours" is triggered right at the start of the backup (it resolves itself seconds later).
I'll post a fix once I figure out what's happening.
[EN-Template Veeam Backup And Replication.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8863503/EN-Template.Veeam.Backup.And.Replication.zip)

**Comment by romainsi** [comment]
Hello, 

I will check this and try to merge quickly.
I confirm you that {#JOBREASON} is working in Operationnal data with Zabbix 6 ...
![veeam](https://user-images.githubusercontent.com/30522413/172779925-0f61418a-43e6-4388-94e5-e11699c01470.png)

**Comment by aholiveira** [comment]
Hello,
New version of the script, template and readme.
The script has been refactored a bit to optimize it and make it simpler to maintain.
The template has been changed to:
 - Solve the early trigger of "job running for more than 8h"
 - Add a graph to the new "job duration" item
 - Add a description on the template
 - Cleanup the "job ended with warning/error" triggers
README was changed to clarify some detail on the SQL user creation.
[zabbix-VB-R-SQL-v22a.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8890585/zabbix-VB-R-SQL-v22a.zip)

**Comment by aholiveira** [comment]
Hello again,
New script version.
- Improved error handling for the SQL connection
- Added comments on the top of script and to each function (get-help zabbix_vbr_job.ps1 now works)
- A few more cleanups
[zabbix-VB-R-SQL-v24.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8904301/zabbix-VB-R-SQL-v24.zip)

**Comment by aholiveira** [comment]
Hello yet again,
Another script version
- More code cleanup
- job reason is now a concatenation of both table column and log_xml information (might have some duplicate information, but we get all the information available for the failure reason)
- New supported job types: Replication backup (1), File backup (2), Agent backup policy (12002) and Agent backup job (12003)

Note that I only created those new job types on my infrastructure but have not actually run them, so we might not get exactly the same information from them. There is no need to change the template, as it will automatically create new items for the new job types.

Side note: You can use ([System.Net.WebUtility]::HtmlEncode($string)) in some of the scripts you have in other repos to convert the strings with accented characters to valid HTML that zabbix can handle, instead of doing the conversions manually (e.g. [this one](https://github.com/romainsi/zabbix-scheduledtask/blob/master/Zabbix%20v3.4/DiscoverScheduledTasks.ps1), line 29)

[zabbix_VB-R-SQL-v25.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8908428/zabbix_VB-R-SQL-v25.zip)

**Comment by stanton79** [comment]
Romainsi,  aholiveira,
this template is just great.
Thanks for your great work

Davide

**Comment by aholiveira** [comment]
Here I am again with a new refactor of this template.
Removed the dependency on zabbix sender. 
Data is now directly sent to zabbix using the script, so it's even faster to execute.

The changes on the script are small:
 - Remove the call to zabbix_sender and replace it with Write-Output
 - Adjust command line arguments to get job and repository information separately

The template had the following changes:
- Get the data directly from the new items which call the script with different arguments
- Minor adjustments to some items

Note: When importing this template version to an existing installation make sure to check "Delete missing" in "Items", "Triggers", "Discovery rules" and "Graphs", to clean up the old items.
[zabbix-VB-R-SQL-v26.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/8934545/zabbix-VB-R-SQL-v26.zip)

**Comment by tashi007** [comment]
Thanks @romainsi and @aholiveira for your great work!

I have one backup job and the result I get for TotalJob is "0", but it does show correct number of Jobs (TotalJob) if the number of backup job is more than 1. Can anyone of you help me resolve this issue.
Thanks,
Tashi

**Comment by aholiveira** [comment]
Hello again. I hadn't noticed that there was already a new release when I did the previous comment.
This script incorporates the changes from the official v2.6 release and the ones I had done on the comment above (proposed v2.7).
[zabbix-VB-R-SQL-v27a.zip](https://github.com/romainsi/zabbix-VB-R-SQL/files/9004450/zabbix-VB-R-SQL-v27a.zip)

**Comment by aholiveira** [comment]
Hello. 
Since I've forked the repository and changes are now being done using pull requests, feel free to close this thread.
