### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by dibreman** [romainsi/zabbix-VB-R-SQL#11]
Hello everyone! 

Here I'm getting this error with returns where the hour is 00. Can anyone help me with it?

Return executing the script in Powershell:

"
New-TimeSpan : Cannot bind parameter 'End'. Cannot convert value "13/05/2022 10:07:12" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At C:\Program Files\Zabbix Agent 2\scripts\zabbix_vbr_job.ps1:154 char:72
+ ...   [String]$result0 = (New-TimeSpan -Start $date -end $newdate).TotalS ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewTimeSpanCommand

New-TimeSpan : Cannot bind parameter 'End'. Cannot convert value "13/05/2022 00:00:06" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At C:\Program Files\Zabbix Agent 2\scripts\zabbix_vbr_job.ps1:154 char:72
+ ...   [String]$result0 = (New-TimeSpan -Start $date -end $newdate).TotalS ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewTimeSpanCommand

New-TimeSpan : Cannot bind parameter 'End'. Cannot convert value "13/05/2022 00:03:36" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At C:\Program Files\Zabbix Agent 2\scripts\zabbix_vbr_job.ps1:159 char:72
+ ...  [String]$result1 = (New-TimeSpan -Start $date -end $newdate0).TotalS ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewTimeSpanCommand
"
With some other jobs, where the value of hour e positive, I have no problem. I think it could be something in conversion process.
I'm newby on Powershell. 

Running on Zabbix 6, MySQL 8. Veeam 11.0.1
Thank you in advance.

**Comment by dibreman** [comment]
Actually, I ran the job in question again, in another time (10:07). The result was the same, with a different time. In the zabbix, this is the message:
Value "13/05/2022 10:22:57" of type "string" is not suitable for value type "Numeric (unsigned)"
But, the curious thing is that on other jobs, the result is right, with no errors.

**Comment by aholiveira-kd** [comment]
Hello,
Replace line 131 with the following:
[System.DateTime]$unixepoch = (get-date -date "01/01/1970 00:00:00Z")

Replace lines 151-162 from the script with these:
        $jobstart = (($job | Where-Object { $_.JobName -like $job.JOBNAME }).JobStart).ToUniversalTime()
        $jobend = (($job | Where-Object { $_.JobName -like $job.JOBNAME }).JobEnd).ToUniversalTime()
        if ($jobstart -lt $unixepoch) {
            $jobstart = $unixepoch.AddSeconds(-1)
        }
        if ($jobend -lt $unixepoch) {
            $jobend = $unixepoch.AddSeconds(-1)
        }
        # Convert to unix timestamp
        $Object | Add-Member -type NoteProperty -Name JOBSTART -Value ([int]((New-TimeSpan -Start $unixepoch -end $jobstart).TotalSeconds))
        $Object | Add-Member -type NoteProperty -Name JOBEND -Value ([int]((New-TimeSpan -Start $unixepoch -end $jobend).TotalSeconds))

This should correctly handle timezones and time conversions.

**Comment by aholiveira** [comment]
Hello,
On line 131, change
`[System.DateTime]$date = (get-date -date "01/01/1970").AddHours(2)`
to
`[System.DateTime]$unixepoch = (get-date -date "01/01/1970 00:00:00Z")`

On lines 151-162, change
```
        if ($jobstart -lt $unixepoch) {
            $jobstart = $unixepoch.AddSeconds(-1)
        }
        if ($jobend -lt $unixepoch) {
            $jobend = $unixepoch.AddSeconds(-1)
        }
        # Convert to unix timestamp
        $Object | Add-Member -type NoteProperty -Name JOBSTART -Value ([int]((New-TimeSpan -Start $unixepoch -end $jobstart).TotalSeconds))
        $Object | Add-Member -type NoteProperty -Name JOBEND -Value ([int]((New-TimeSpan -Start $unixepoch -end $jobend).TotalSeconds))
```
to

```
        $jobstart = (($job | Where-Object { $_.JobName -like $job.JOBNAME }).JobStart).ToUniversalTime()
        $jobend = (($job | Where-Object { $_.JobName -like $job.JOBNAME }).JobEnd).ToUniversalTime()
        if ($jobstart -lt $unixepoch) {
            $jobstart = $unixepoch.AddSeconds(-1)
        }
        if ($jobend -lt $unixepoch) {
            $jobend = $unixepoch.AddSeconds(-1)
        }
        # Convert to unix timestamp
        $Object | Add-Member -type NoteProperty -Name JOBSTART -Value ([int]((New-TimeSpan -Start $unixepoch -end $jobstart).TotalSeconds))
        $Object | Add-Member -type NoteProperty -Name JOBEND -Value ([int]((New-TimeSpan -Start $unixepoch -end $jobend).TotalSeconds))

```
This should correctly handle timezones and time conversions.

**Comment by romainsi** [comment]
Hello,

The error in script has been corrected following the refactored of the script by [aholiveira](https://github.com/aholiveira).
Check new release.

Regards,
Romain.
