### ISSUE TITLE
Is production ready?

### ISSUE THREAD

**Issue by ArcaneDiver** [romainsi/zabbix-VB-R-SQL#2]
Hi,
i would know if this template is production ready and I would like to know which one should I actually choose between the old template and this one.

**Comment by romainsi** [comment]
Hi,

I use it in production but it's up to you to make your choice.
The old version uses the Veeam module for Powershell, this version queries the sql database.
The queries are faster and have less chance to end in timeout.

**Comment by ArcaneDiver** [comment]
Ok, thank you very much for the reply!
