### ISSUE TITLE
Totaljob returns no info.  Jobsinfo returns []

### ISSUE THREAD

**Issue by mayflowertech** [romainsi/zabbix-VB-R-SQL#24]
latest version, zabbix 6 veeam 11.  Every other metric is working as intended.  Jobsinfo does not return anything, and total job just returns brackets.  

Verified using just powershell as well so I don't think it's anything lost in translation going to zabbix.

Thank you for your hard work.

**Comment by aholiveira** [comment]
Hello,
Thank for you words.
1 - If you run the script with "JobsInfo" and "-Debug" parameters what is the output?
2 - Have you checked the user permissions on SQL side?
3 - Is this a fresh install of the plugin or an upgrade from previous versions? If it is an upgrade, did you unlink and clear?

Read this issue https://github.com/romainsi/zabbix-VB-R-SQL/issues/23 which could be a similar situation.

Regards,
Antonio Oliveira

**Comment by mayflowertech** [comment]
Excellent troubleshooting!  The debug allowed me to see that the database was not connecting due to not using fqdn\instance name.

Thank you very much for your help and the wonderful script!

**Comment by aholiveira** [comment]
Great. Can you close the issue then? Thanks.
