### ISSUE TITLE
problems with server instance

### ISSUE THREAD

**Issue by Uga4aka** [romainsi/zabbix-VB-R-SQL#3]
for example
if you specify the variable $veeamserver = 'veeam.contoso.local'
then there will be no connection to the server that has its own sql instance. there will be a connection error.
the variable must be specified then $veeamserver = 'veeam.contoso.local \ sqlexpress2016,65294'
but with such a connection the repo detection will not pass due to wmi request error
I decided for myself to add the second variable $veeamrepo = 'veeam.contoso.local' which is used in the wmi request

**Comment by romainsi** [comment]
Hi,

True, but in SQL server, in user parameters if you set the default database, no need to specify.
I modify the readme accordingly.
