### ISSUE TITLE
Compatibility Veeam 11 ?

### ISSUE THREAD

**Issue by tabtab-ops** [romainsi/zabbix-VB-R-SQL#4]
Hello,
Is this template OK with Veeam 11 ?
Veeam 11.0.0.837 if it could help ;)
Thus, no data in Zabbix (5.4.1)

Thanks
Nicolas

**Comment by tabtab-ops** [comment]
Veeam 11.0.0.837 if it could help ;)
Thanks
Nicolas

**Comment by IA-SnipeIT** [comment]
Hello!
I am also on Veeam 11. Zabbix version is 5.0.14. I followed the link below and was able to get the template and ps script communicating with Zabbix but still not getting the majority of the information from Veeam into Zabbix that I'd like to get such as a list of all the jobs their statuses etc. I've included screen captures. Is there any fix for this or advice? 
Thanks!
Jason

> https://github.com/romainsi/zabbix-VB-R-SQL/issues/1

Zabbix reporting "Nombre de travaux VEEAM Total" and "Start All Jobs" but nothing else. I've included some screen shots.

![veeam-zabbix-1](https://user-images.githubusercontent.com/78383431/129229241-8cdfd6c8-ea01-443f-9954-bcec491d0278.png)
![veeam-zabbix-2](https://user-images.githubusercontent.com/78383431/129229450-e1825b3d-966b-4409-930d-07f9e4c25d8b.png)

**Comment by TarrX** [comment]
I've experienced this error, albeit with Veeam 9, with a not properly setup environment. I seemed to work a little bit but did not really work. Things I did to get it running was fix an improper value for the active proxy and increase the timeout to 30 seconds for the proxy aswell.

**Comment by IA-SnipeIT** [comment]
> I've experienced this error, albeit with Veeam 9, with a not properly setup environment. I seemed to work a little bit but did not really work. Things I did to get it running was fix an improper value for the active proxy and increase the timeout to 30 seconds for the proxy aswell.

Thanks for the input. I'm not using a proxy but what parameter are these exactly and where and perhaps I can adjust on the Zabbix server to see if this has any affect on the issue. Thanks.

**Comment by TarrX** [comment]
> Thanks for the input. I'm not using a proxy but what parameter are these exactly and where and perhaps I can adjust on the Zabbix server to see if this has any affect on the issue. Thanks.
zabbix_server.conf, the Timeout parameter, for testing purpose you could set it to the max, which is 30 (seconds). Also it might be helpful to increase DebugLevel to see what is going on, log file is at /var/log/zabbix, usually.

**Comment by IA-SnipeIT** [comment]
Thanks for the tips. They were helpful.

Jason Ladew
Senior IT Project Manager
Inductive Automation
1.800.266.7798 ext. 250 (Within USA)
1.916.456.1045 ext. 250 (International)
[image: Inductive Automation] <https://inductiveautomation.com/>

**Comment by rootdamage** [comment]
Hi everyone , i have Zabbix 5.x.x and Veeam 11 version . That script not working and no generate xml file in C:\Program Files\Zabbix Agent\scripts . Who faced and now solved this problem?..

**Comment by noobas911** [comment]
> Hi everyone , i have Zabbix 5.x.x and Veeam 11 version . That script not working and no generate xml file in C:\Program Files\Zabbix Agent\scripts . Who faced and now solved this problem?.. In loggs agent : 8568:20210831:074755.221 active check "system.run[powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1" exportxml,nowait]" is not supported: Unsupported item key.

Hi, i edit posh script and it work with veeam 11 and zabbix 5.4.*
try to replace `$query = $BackupJobs| Where-Object { $_.Schedule_Enabled -like "true"  -and $_.Type -like "51"}` to `$query = $BackupJobs `
that select all your jobs from sql db
Veeam change values in tables, sql querys need changes

if you using named sql instance replace all this strings
`Get-CimInstance -Class Repository -ComputerName  'place veeam hostname' -Namespace ROOT\VeeamBS `

and you need enable active check at your zabbix server and config zabbix agent for using it (agent hostname is 
case sensitive)

**Comment by abenitezuy** [comment]
Is there a script working in Veeam 11 and Zabbix Server 6.0rc2, agent must be active or could be passive ?
