### ISSUE TITLE
New Template and Zabbix Agent 2 not compatible with 5.0.14

### ISSUE THREAD

**Issue by ia-jladew** [romainsi/zabbix-VB-R-SQL#5]
Hello!
I notice that you had updated the Veeam template to work with Zabbix Agent 2 a couple of days ago. I followed the instructions and it appears it is not supported in v5.0.14. I can't import YAML template. When I attempt to import the XML it first complains about the version in the XML that it is 5.4. I change this to 5.0 and it does not work as it is complaining about UUIDs and TAGS. Do you have any suggests?
Thanks
Jason

**Comment by romainsi** [comment]
There have been many changes since 5.0 ... I don't guarantee anything :smirk:
Try with [this template](https://github.com/romainsi/zabbix-VB-R-SQL/blob/Test/Zabbix5.0-Template%20Veeam%20Backup%20And%20Replication.xml) and remember to check the triggers.

**Comment by ia-jladew** [comment]
I'm just happy and appreciate the time you put into creating something like this for us. Thanks.
