### ISSUE TITLE
English version available?

### ISSUE THREAD

**Issue by ugoviti** [romainsi/zabbix-VB-R-SQL#6]
Hi, thank you for your template, in the latest commits is present only French version, can you upload English version also?
keep up good work. 
Kind Regards

**Comment by romainsi** [comment]
Hi,

I add a new template in English : https://github.com/romainsi/zabbix-VB-R-SQL/blob/main/EN-Template%20Veeam%20Backup%20And%20Replication.yaml.

**Comment by ugoviti** [comment]
Thank you very much!
