### ISSUE TITLE
Plugin not working properly

### ISSUE THREAD

**Issue by blaugrau90** [romainsi/zabbix-VB-R-SQL#9]
Hello, 

I have implemented the plugin as you described. Unfortunately, somehow it does not work and I can not figure out why it does not work. The PS script always shows only "-- ERROR -- : Need an option !" and in zabbix also no data arrive, but mostly only the note "Unknown metric vbr". 

I can't get any further. Can you help me?

**Comment by romainsi** [comment]
Hello,

Please use new release and follow the Setup in Readme.
 `-- ERROR -- : Need an option !` indicates that the script is waiting for an argument (example with 'StartJobs') :
.\zabbix_vbr_job.ps1 StartJobs

Regards,
Romain.

**Comment by aholiveira** [comment]
Hello @blaugrau90,
There have been a number of changes on both the templates and the script.
Can you download the latest version and try with that one?
Please use the following steps:
1 - "Unlink and clear" the template from any hosts using it
2 - Delete the template from Zabbix
3 - Replace the script with the new version
4 - Configure variables on the script with appropriate values
5 - Import new version of the template to Zabbix
6 - Link the template to the Veeam host

You should now be able to get data from Veeam into Zabbix.
Please comment here the result so we can either try to help if it is still not working or close the issue if it now works.

Regards.

**Comment by thmcon** [comment]
Hallo @aholiveira,
I just applied the new version as descibed by you.
I can report back, that veeam shows the total number of jobs, job info, repository info.
Looks like it works. 
I will report back in case something does not work any more or if results are wrong after veeam jobs have been operated.
Thanks!
Thomas
